# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Shubham Aher || Blog
tagline:          'Reverse Engineering'
description:      '23. Hardcore Cancerian. Yuppie. Hobby Juggler. Single. Hailing from Nasik. Living in Pune.'
url:              http://shubhamaher.com
baseurl:          /

author:
  name:           'Shubham Aher'
  url:            https://twitter.com/shubham_aher

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shubham-aher
